### ISSUE TITLE
CMakeLists file not packaged in the libvorbis.tar.gz file 

### ISSUE THREAD

**Issue by martinRenou** [xiph/vorbis#61] opened 2020-03-23 09:43 UTC
It looks like the `CMakeLists.txt` file is not packaged in the `http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.gz` file. But it is needed for building with cmake. Is it not packaged on purpose? Or could it be done?

**Comment by rillian** [comment] 2020-03-23 15:06
This has been done, but it was after the last release was published. We'll need to do a new release so the cmake build is available. In the meantime, you'll have to build out of git.

**Comment by rillian** [comment] 2020-03-23 15:13
Closing as a duplicate of #32.

**Closed by rillian** 2020-03-23 15:13 UTC

**Comment by martinRenou** [comment] 2020-03-23 15:19
Oh sorry for the duplicate then! Thank you

**Comment by rillian** [comment] 2020-03-23 18:54
No problem. It's good to be reminded we need to make another release.
